import {
  LuLaptop,
  LuMonitor,
  LuServer,
  LuPrinter,
  LuMouse,
  LuPenTool,
  LuArmchair,
  LuHardDrive,
  LuVideo,
  LuPackage,
  LuShield,
  LuFolder,
  LuFile,
  LuPen,
  LuScissors,
  LuTerminal,
  LuLayers2,
  LuPaperclip,
} from 'react-icons/lu';

export const CategoryIcons: Record<string, React.ReactNode> = {
  '12': <LuServer />,
  '14': <LuMonitor />,
  '15': <LuServer />,
  '16': <LuHardDrive />,
  '17': <LuVideo />,
  '18': <LuPackage />,
  '19': <LuServer />,
  '20': <LuHardDrive />,
  '21': <LuServer />,
  '22': <LuShield />,
  '23': <LuHardDrive />,
  '24': <LuShield />,
  '25': <LuTerminal />,
  '26': <LuTerminal />,
  '36': <LuLaptop />,
  '37': <LuLaptop />,
  '38': <LuLaptop />,
  '39': <LuLaptop />,
  '40': <LuPrinter />,
  '41': <LuMouse />,
  '42': <LuLayers2 />,
  '43': <LuLayers2 />,
  '44': <LuLayers2 />,
  '45': <LuLayers2 />,
  '46': <LuLayers2 />,
  '47': <LuArmchair />,
  '48': <LuArmchair />,
  '49': <LuArmchair />,
  '50': <LuArmchair />,
  '51': <LuFile />,
  '52': <LuFile />,
  '53': <LuFile />,
  '54': <LuPen />,
  '55': <LuScissors />,
  '56': <LuPaperclip />,
  '57': <LuFolder />,
  '58': <LuPenTool />,
  '59': <LuPenTool />,
  '60': <LuFolder />,
};
